/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerenciamentoeventos;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class PainelEventos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelEventos.class.getName());
    
    String modalidade, situacao;
    
    private Arquivo arquivo;
    private ArrayList<Evento> listaEventos;
    private int linhaEdicao = -1;
    public PainelEventos() {
        initComponents();
        btn_grp_modalidade.add(rdo_presencial);
        btn_grp_modalidade.add(rdo_online);
        btn_grp_situacao.add(rdo_agendado);
        btn_grp_situacao.add(rdo_realizado);
        btn_grp_situacao.add(rdo_cancelado);
        arquivo = new Arquivo("Eventos");
        listaEventos = arquivo.leArquivo();
    }
    private void carregarTabela(){
        DefaultTableModel tabela = (DefaultTableModel) tbl_eventos.getModel();
        tabela.setRowCount(0);
        
        for(Evento e : listaEventos){
            tabela.addRow(e.ObterDados());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_grp_modalidade = new javax.swing.ButtonGroup();
        btn_grp_situacao = new javax.swing.ButtonGroup();
        cmb_tipo = new javax.swing.JComboBox<>();
        lbl_tipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdo_presencial = new javax.swing.JRadioButton();
        rdo_online = new javax.swing.JRadioButton();
        rdo_agendado = new javax.swing.JRadioButton();
        lbl_situacao = new javax.swing.JLabel();
        rdo_realizado = new javax.swing.JRadioButton();
        rdo_cancelado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_eventos = new javax.swing.JTable();
        btn_cadastrar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        nome = new javax.swing.JLabel();
        txt_nome_evento = new javax.swing.JTextField();
        lbl_data = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        lbl_local = new javax.swing.JLabel();
        txt_local = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Palestra", "Workshop", "Curso", "Conferência", " " }));

        lbl_tipo.setText("tipo");

        jLabel1.setText("modalidade");

        rdo_presencial.setText("Presencial");

        rdo_online.setText("Online");

        rdo_agendado.setText("Agendado");

        lbl_situacao.setText("Situação");

        rdo_realizado.setText("Realizado");

        rdo_cancelado.setText("Cancelado");

        tbl_eventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome evt", "data", "local", "tipo", "modalidade", "situação"
            }
        ));
        jScrollPane1.setViewportView(tbl_eventos);

        btn_cadastrar.setText("Cadastrar/Salvar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        nome.setText("Nome");

        txt_nome_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_eventoActionPerformed(evt);
            }
        });

        lbl_data.setText("Data");

        txt_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataActionPerformed(evt);
            }
        });

        lbl_local.setText("Local");

        txt_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_localActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_situacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdo_agendado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdo_realizado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdo_presencial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdo_online)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_cancelado)
                                .addGap(78, 78, 78))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nome)
                                    .addComponent(lbl_tipo))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_nome_evento))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_data)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_local)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_local)))
                                .addGap(31, 31, 31)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome)
                            .addComponent(txt_nome_evento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_data)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_tipo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_local)
                                .addComponent(txt_local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo_online)
                            .addComponent(rdo_presencial)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_situacao)
                            .addComponent(rdo_agendado)
                            .addComponent(rdo_realizado)
                            .addComponent(rdo_cancelado)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
      //logica da modalidade
      if(rdo_presencial.isSelected()){
          modalidade = "Presencial";
      }
      if(rdo_online.isSelected()){
          modalidade = "Online";
      }  
      // logica da situacao
      if(rdo_cancelado.isSelected()){
          situacao = "Cancelado";
      }
      if(rdo_agendado.isSelected()){
          situacao = "Agendado";
      }
      if(rdo_realizado.isSelected()){
          situacao = "Realizado";
      }
      String tipo = cmb_tipo.getSelectedItem()+"";
      Evento e = new Evento(
       txt_nome_evento.getText(),
       txt_data.getText(),
       txt_local.getText(),
      (String)cmb_tipo.getSelectedItem(),
       modalidade,
       situacao
      );
      if(linhaEdicao == -1){
            listaEventos.add(e);
        }else{
            listaEventos.set(linhaEdicao, e);
            linhaEdicao = -1;
        }
        arquivo.gravaArquivo();
        carregarTabela();
        JOptionPane.showMessageDialog(null, "Dados do Evento Salvos com sucesso!");
        System.out.println("Evento add");
        for(Evento evento : listaEventos){
            System.out.println(evento);
        }
        carregarTabela();
        txt_nome_evento.setText("");
        txt_data.setText("");
        txt_local.setText("");
        btn_grp_situacao.clearSelection();
        btn_grp_modalidade.clearSelection();
        cmb_tipo.setSelectedIndex(0);
      
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_nome_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_eventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nome_eventoActionPerformed

    private void txt_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataActionPerformed

    private void txt_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_localActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_localActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
       int linha = tbl_eventos.getSelectedRow();
       if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um evento para editar!");
            return;
       }
       linhaEdicao = linha;
       Evento e = listaEventos.get(linha);
       txt_nome_evento.setText(e.nomeEvento);
       txt_data.setText(e.data+"");
       txt_local.setText(e.local+"");
       //modalidade
       if(e.modalidade.equalsIgnoreCase(modalidade)){
           rdo_presencial.setSelected(true);
       }
       if(e.modalidade.equalsIgnoreCase(modalidade)){
           rdo_online.setSelected(true);
       }
       
        //situacao
       if(e.situacao.equalsIgnoreCase(situacao)){
           rdo_agendado.setSelected(true);
       }
       if(e.situacao.equalsIgnoreCase(situacao)){
           rdo_realizado.setSelected(true);
       }
       if(e.situacao.equalsIgnoreCase(situacao)){
           rdo_cancelado.setSelected(true);
       }
       cmb_tipo.setSelectedItem(e.tipo);
    }//GEN-LAST:event_btn_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelEventos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_editar;
    private javax.swing.ButtonGroup btn_grp_modalidade;
    private javax.swing.ButtonGroup btn_grp_situacao;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_local;
    private javax.swing.JLabel lbl_situacao;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel nome;
    private javax.swing.JRadioButton rdo_agendado;
    private javax.swing.JRadioButton rdo_cancelado;
    private javax.swing.JRadioButton rdo_online;
    private javax.swing.JRadioButton rdo_presencial;
    private javax.swing.JRadioButton rdo_realizado;
    private javax.swing.JTable tbl_eventos;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_local;
    private javax.swing.JTextField txt_nome_evento;
    // End of variables declaration//GEN-END:variables
}
