
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laboratorio
 */
public class Formulario2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario2.class.getName());

    /**
     * Creates new form Formulario2
     */
    char sexo;
    boolean tecnologia, astronomia, esportes;
    private Arquivo arquivo;
    private ArrayList<Pessoa> listaPessoas;
    public Formulario2() {
        initComponents();
        arquivo = new Arquivo("pessoas");
        listaPessoas = arquivo.leArquivo();
        carregarTabela();
    }
    private void carregarTabela(){
        DefaultTableModel tabela = (DefaultTableModel) tbl_pessoas.getModel();
        
        tabela.setRowCount(0);
        
        for(Pessoa p : listaPessoas){
            tabela.addRow(p.obterDados());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        rdoMasculino = new javax.swing.JRadioButton();
        rdoFeminino = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        chk_Tecnologia = new javax.swing.JCheckBox();
        chk_Astronomia = new javax.swing.JCheckBox();
        chk_Esportes = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cmb_Idioma = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pessoas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Sexo");

        btnGrpSexo.add(rdoMasculino);
        rdoMasculino.setText("Masculino");

        btnGrpSexo.add(rdoFeminino);
        rdoFeminino.setText("Feminino");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        chk_Tecnologia.setText("Tecnologia");

        chk_Astronomia.setText("Astronomia");

        chk_Esportes.setText("Esportes");
        chk_Esportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_EsportesActionPerformed(evt);
            }
        });

        jLabel3.setText("Interesses");

        cmb_Idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espanhol", "Inglês", "Português" }));

        jLabel4.setText("Idioma");

        tbl_pessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Idioma"
            }
        ));
        jScrollPane1.setViewportView(tbl_pessoas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(rdoFeminino))
                            .addComponent(chk_Tecnologia)
                            .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chk_Astronomia))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(chk_Esportes)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdoMasculino)
                    .addComponent(rdoFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_Tecnologia)
                    .addComponent(chk_Astronomia)
                    .addComponent(chk_Esportes)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(rdoMasculino.isSelected()){
           // JOptionPane.showMessageDialog(null, txtNome.getText()+" - Sexo Masculino",
                  //  "Alerta", JOptionPane.OK_OPTION);
            sexo = 'M';
        }
        else if(rdoFeminino.isSelected()){
           // JOptionPane.showMessageDialog(null, txtNome.getText()+" - Sexo Feminino", 
             //       "Alerta", JOptionPane.OK_OPTION);
            sexo = 'F';
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um sexo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        tecnologia = chk_Tecnologia.isSelected();
        astronomia = chk_Astronomia.isSelected();
        esportes = chk_Esportes.isSelected();
    
       // JOptionPane.showMessageDialog(null, "Tecnologia: "+tecnologia+
            //    " Astrononomia: "+astronomia+
              //  " Esportes: "+esportes, "Alerta", JOptionPane.INFORMATION_MESSAGE);

        String idioma = cmb_Idioma.getSelectedItem()+"";
        //JOptionPane.showMessageDialog(null, "Idioma: "+idioma
            //    ,"Alerta", JOptionPane.INFORMATION_MESSAGE);
        //Pessoa p = new Pessoa (txtNome.getText(), sexo, idioma);
        Pessoa p = new Pessoa (txtNome.getText(), sexo, (String)cmb_Idioma.getSelectedItem());
        DefaultTableModel tabela = (DefaultTableModel) tbl_pessoas.getModel();
        tabela.addRow(p.obterDados());
        
        listaPessoas.add(p);
        
        arquivo.gravaArquivo();
        
        System.out.println("Pessoa add");
        for(Pessoa pessoa : listaPessoas){
            System.out.println(pessoa);
        }
        
        carregarTabela();
        txtNome.setText("");
        btnGrpSexo.clearSelection();
        chk_Tecnologia.setSelected(false);
        chk_Astronomia.setSelected(false);
        chk_Esportes.setSelected(false);
        cmb_Idioma.setSelectedIndex(0);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chk_EsportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_EsportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_EsportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpSexo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chk_Astronomia;
    private javax.swing.JCheckBox chk_Esportes;
    private javax.swing.JCheckBox chk_Tecnologia;
    private javax.swing.JComboBox<String> cmb_Idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoFeminino;
    private javax.swing.JRadioButton rdoMasculino;
    private javax.swing.JTable tbl_pessoas;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
