/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author laboratorio
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_arquivo = new javax.swing.JMenu();
        menu_item_sair = new javax.swing.JMenuItem();
        menu_cadastro = new javax.swing.JMenu();
        menu_item_cadastro = new javax.swing.JMenuItem();
        menu_item_editar_excluir = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        menu_item_relatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_arquivo.setText("Arquivo ");
        menu_arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_arquivoActionPerformed(evt);
            }
        });

        menu_item_sair.setText("Sair");
        menu_item_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_sairActionPerformed(evt);
            }
        });
        menu_arquivo.add(menu_item_sair);

        jMenuBar1.add(menu_arquivo);

        menu_cadastro.setText("Cadastro");
        menu_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cadastroActionPerformed(evt);
            }
        });

        menu_item_cadastro.setText("Cadastro de Pessoas");
        menu_item_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cadastroActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_item_cadastro);

        menu_item_editar_excluir.setText("Editar e excluir Pessoas");
        menu_item_editar_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_editar_excluirActionPerformed(evt);
            }
        });
        menu_cadastro.add(menu_item_editar_excluir);

        jMenuBar1.add(menu_cadastro);

        menu_relatorio.setText("Relatorio");
        menu_relatorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menu_relatorioItemStateChanged(evt);
            }
        });
        menu_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_relatorioActionPerformed(evt);
            }
        });

        menu_item_relatorio.setText("Relatorios");
        menu_item_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_relatorioActionPerformed(evt);
            }
        });
        menu_relatorio.add(menu_item_relatorio);

        jMenuBar1.add(menu_relatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cadastroActionPerformed
       FormCadastroPessoa cadPessoa = new FormCadastroPessoa();
      cadPessoa.setVisible(true);
    }//GEN-LAST:event_menu_item_cadastroActionPerformed

    private void menu_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cadastroActionPerformed
      
    }//GEN-LAST:event_menu_cadastroActionPerformed

    private void menu_item_editar_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_editar_excluirActionPerformed
       FormConsultaPessoa conPessoa = new FormConsultaPessoa();
       conPessoa.setVisible(true);
    }//GEN-LAST:event_menu_item_editar_excluirActionPerformed

    private void menu_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_relatorioActionPerformed
      
    }//GEN-LAST:event_menu_relatorioActionPerformed

    private void menu_relatorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menu_relatorioItemStateChanged
       
    }//GEN-LAST:event_menu_relatorioItemStateChanged

    private void menu_item_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_relatorioActionPerformed
        RelatorioPessoas relPessoas = new RelatorioPessoas();
       relPessoas.setVisible(true);
    }//GEN-LAST:event_menu_item_relatorioActionPerformed

    private void menu_arquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_arquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_arquivoActionPerformed

    private void menu_item_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_sairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menu_item_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_arquivo;
    private javax.swing.JMenu menu_cadastro;
    private javax.swing.JMenuItem menu_item_cadastro;
    private javax.swing.JMenuItem menu_item_editar_excluir;
    private javax.swing.JMenuItem menu_item_relatorio;
    private javax.swing.JMenuItem menu_item_sair;
    private javax.swing.JMenu menu_relatorio;
    // End of variables declaration//GEN-END:variables
}
