/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leo zorzi
 */
public class PainelBiblioteca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelBiblioteca.class.getName());

    char emprestado;
    private Arquivo arquivo;
    private ArrayList<Livro> listaLivros;
    private int linhaEdicao = -1;
    public PainelBiblioteca() {
        initComponents();
        arquivo = new Arquivo("livros");
        listaLivros = arquivo.leArquivo();
    }
     private void carregarTabela(){
        DefaultTableModel tabela = (DefaultTableModel) tbl_livros.getModel();
        tabela.setRowCount(0);
        
        for(Livro l: listaLivros){
            tabela.addRow(l.obterDados());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_titulo = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        txt_ano = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        lbl_autor = new javax.swing.JLabel();
        lbl_ano = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_devolver = new javax.swing.JButton();
        bnt_emprestar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_livros = new javax.swing.JTable();
        cmb_genero = new javax.swing.JComboBox<>();
        lbl_genero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_autor.addActionListener(this::txt_autorActionPerformed);

        lbl_titulo.setText("titulo");

        lbl_autor.setText("autor");

        lbl_ano.setText("ano");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(this::btn_cadastrarActionPerformed);

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(this::btn_excluirActionPerformed);

        btn_editar.setText("Editar");
        btn_editar.addActionListener(this::btn_editarActionPerformed);

        btn_devolver.setText("Devolver");
        btn_devolver.addActionListener(this::btn_devolverActionPerformed);

        bnt_emprestar.setText("Emprestar");
        bnt_emprestar.addActionListener(this::bnt_emprestarActionPerformed);

        tbl_livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Autor", "Ano", "Leitor", "Genero", "Emprestado"
            }
        ));
        jScrollPane1.setViewportView(tbl_livros);

        cmb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drama", "Ação", "Ficção", "Romance", "Psicanalise", "Religião", " " }));

        lbl_genero.setText("genero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_ano)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_autor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_titulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_genero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnt_emprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_devolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_titulo)
                            .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_autor))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ano))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_genero)
                                    .addComponent(cmb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bnt_emprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String genero = cmb_genero.getSelectedItem()+"";
        emprestado = 'N';
        Livro l = new Livro(
        txt_titulo.getText(),
        txt_autor.getText(),
        (String)cmb_genero.getSelectedItem(), 
        Integer.parseInt(txt_ano.getText()),
        'N', //status de nao emprestado
        "" // nome do autor que so ao pegar emprestado
        );
         if(linhaEdicao == -1){
            listaLivros.add(l);
        }else{
            listaLivros.set(linhaEdicao, l);
            linhaEdicao = -1;
        }
        arquivo.gravaArquivo();
        carregarTabela();
        JOptionPane.showMessageDialog(null, "Dados do Livro Salvos com sucesso!");
        System.out.println("Livro add");
        for(Livro livro : listaLivros){
            System.out.println(livro);
        }
        carregarTabela();
        txt_titulo.setText("");
        txt_autor.setText("");
        txt_ano.setText("");
        cmb_genero.setSelectedIndex(0);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
       int linha = tbl_livros.getSelectedRow();
       if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um Livro para editar!");
            return;
       }
       linhaEdicao = linha;
       Livro l = listaLivros.get(linha);
       txt_titulo.setText(l.titulo);
       txt_autor.setText(l.autor);
       txt_ano.setText(l.ano_lancamento+"");
       
       cmb_genero.setSelectedItem(l.genero);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tbl_livros.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(null, "selelcione um livro da tabela.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int resultado = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir este livro?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION){
            listaLivros.remove(linha);
            
            arquivo.gravaArquivo();
            
            carregarTabela();
            
            System.out.println("Livro Excluido!!");
        } 
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolverActionPerformed
       int linha = tbl_livros.getSelectedRow();
       if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um Livro para devolver!");
            return;
       }
       linhaEdicao = linha;
        Livro l = listaLivros.get(linha);
        if(l.emprestado == 'N'){
            JOptionPane.showMessageDialog(null, "Livro não emprestado!");
            return;
        }
        l.emprestado = 'N'; //qnd devolve retorna que nao esta emprestado
        l.nomeLeitor = ""; // e o nome do leitor some pq ja devolveu
        
        arquivo.gravaArquivo();
        carregarTabela();
    }//GEN-LAST:event_btn_devolverActionPerformed

    private void bnt_emprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_emprestarActionPerformed
        int linha = tbl_livros.getSelectedRow();
       if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um Livro!");
            return;
       }
        Livro l = listaLivros.get(linha);
        if(l.emprestado == 'S'){
            JOptionPane.showMessageDialog(null, "Livro já emprestado!");
            return;
        }
        String nome = JOptionPane.showInputDialog("Digite o nome do leitor: ");
        if(nome == null || nome.trim().isEmpty()){
            System.out.println("cancelou");
            return;
        }
        l.emprestado = 'S';
        l.nomeLeitor = nome;
        
        arquivo.gravaArquivo();
        carregarTabela();
        
    }//GEN-LAST:event_bnt_emprestarActionPerformed

    private void txt_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_emprestar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_devolver;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JComboBox<String> cmb_genero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ano;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTable tbl_livros;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
