/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastroproduto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leo zorzi
 */
public class PainelProduto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelProduto.class.getName());

    /**
     * Creates new form painelProduto
     */
     char disponivel;
     
    private Arquivo arquivo;
    private ArrayList<Produto> listaProdutos;
    private int linhaEdicao = -1;
    public PainelProduto() {
        initComponents();
        // setar os rdos no btn group para nao ser possivel marcar dois ao mesmo tempo
        btn_grp_disponivel.add(rdo_sim);
        btn_grp_disponivel.add(rdo_nao);
        arquivo = new Arquivo("produtos");
        listaProdutos = arquivo.leArquivo();
        carregarTabela();
    }
    private void carregarTabela(){
        DefaultTableModel tabela = (DefaultTableModel) tbl_produtos.getModel();
        tabela.setRowCount(0);
        
        for(Produto p: listaProdutos){
            tabela.addRow(p.obterDados());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_grp_disponivel = new javax.swing.ButtonGroup();
        txt_nome = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        cmb_categoria = new javax.swing.JComboBox<>();
        lbl_categoria = new javax.swing.JLabel();
        txt_preco = new javax.swing.JTextField();
        lbl_preco = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();
        lbl_quantidade = new javax.swing.JLabel();
        rdo_sim = new javax.swing.JRadioButton();
        rdo_nao = new javax.swing.JRadioButton();
        lbl_disponivel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_produtos = new javax.swing.JTable();
        btn_cadastrar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nome.setText("Produto:");

        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eletrônico", "Alimento", "Vestuário", "Limpeza" }));

        lbl_categoria.setText("categoria:");

        txt_preco.addActionListener(this::txt_precoActionPerformed);

        lbl_preco.setText("preco");

        lbl_quantidade.setText("quantidade");

        rdo_sim.setText("Sim");

        rdo_nao.setText("Não");

        lbl_disponivel.setText("disponivel");

        tbl_produtos.setForeground(new java.awt.Color(0, 102, 102));
        tbl_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome Produto", "Categoria", "Preço", "Quantidade", "Disponibildade"
            }
        ));
        jScrollPane1.setViewportView(tbl_produtos);

        btn_cadastrar.setText("Cadastrar/Salvar");
        btn_cadastrar.addActionListener(this::btn_cadastrarActionPerformed);

        btn_editar.setText("Editar");
        btn_editar.addActionListener(this::btn_editarActionPerformed);

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(this::btn_excluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nome)
                            .addComponent(lbl_preco)
                            .addComponent(lbl_quantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_quantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txt_preco)
                            .addComponent(txt_nome))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_categoria)
                            .addComponent(lbl_disponivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdo_sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_nao))
                            .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nome)
                    .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_categoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdo_sim)
                        .addComponent(rdo_nao)
                        .addComponent(lbl_disponivel))
                    .addComponent(lbl_preco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_quantidade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_precoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        if(rdo_sim.isSelected()){
            disponivel = 'S';
        }
        else if(rdo_nao.isSelected()){
            disponivel = 'N';
        }
        else{
             JOptionPane.showMessageDialog(null, "Selecione um campo para seguir", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        String categoria = cmb_categoria.getSelectedItem()+"";
        Produto p = new Produto(txt_nome.getText(),
                        (String)cmb_categoria.getSelectedItem(),
                        Double.parseDouble(txt_preco.getText()), 
                        Integer.parseInt(txt_quantidade.getText()), 
                        disponivel);
        if(linhaEdicao == -1){
            listaProdutos.add(p);
        }else{
            listaProdutos.set(linhaEdicao, p);
            linhaEdicao = -1;
        }
        arquivo.gravaArquivo();
        carregarTabela();
        JOptionPane.showMessageDialog(null, "Dados do Produto Salvos com sucesso!");
        System.out.println("Produto add");
        for(Produto produto : listaProdutos){
            System.out.println(produto);
        }
        carregarTabela();
        txt_nome.setText("");
        txt_preco.setText("");
        txt_quantidade.setText("");
        btn_grp_disponivel.clearSelection();
        cmb_categoria.setSelectedIndex(0);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
       int linha = tbl_produtos.getSelectedRow();
       if(linha == -1){
            JOptionPane.showMessageDialog(null, "Selecione um produto para editar!");
            return;
       }
       linhaEdicao = linha;
       Produto p = listaProdutos.get(linha);
       txt_nome.setText(p.nome);
       txt_preco.setText(p.preco+"");
       txt_quantidade.setText(p.quantidade+"");
       
       if(p.disponivel == 'S'){
           rdo_sim.setSelected(true);
       }
       else{
           rdo_nao.setSelected(true);
       }
       cmb_categoria.setSelectedItem(p.categoria);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tbl_produtos.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(null, "selelcione um produto da tabela.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int resultado = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir este produto?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION){
            listaProdutos.remove(linha);
            
            arquivo.gravaArquivo();
            
            carregarTabela();
            
            System.out.println("Produto Excluido!!");
        }
    }//GEN-LAST:event_btn_excluirActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.ButtonGroup btn_grp_disponivel;
    private javax.swing.JComboBox<String> cmb_categoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_disponivel;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_quantidade;
    private javax.swing.JRadioButton rdo_nao;
    private javax.swing.JRadioButton rdo_sim;
    private javax.swing.JTable tbl_produtos;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_quantidade;
    // End of variables declaration//GEN-END:variables
}
