/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Beans.Professor;
import DAO.ProfessorDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author leo zorzi
 */
public class FormConsultaProfessor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormConsultaProfessor.class.getName());

    /**
     * Creates new form FormConsultaProfessor
     */
    public FormConsultaProfessor() {
        initComponents();
    }
      public void limparFormulario(){
        txt_id2.setText("");
        txt_id.setText("");
        txt_nome.setText("");
        txt_idade.setText("");
        cmb_disciplinas.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idade = new javax.swing.JTextField();
        lbl_disciplina = new javax.swing.JLabel();
        cmb_disciplinas = new javax.swing.JComboBox<>();
        txt_nome = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        bnt_atualizar = new javax.swing.JButton();
        lbl_id2 = new javax.swing.JLabel();
        btn_excluir = new javax.swing.JButton();
        txt_id2 = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        btn_consultar = new javax.swing.JButton();
        lbl_idade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_disciplina.setText("Disciplina");

        cmb_disciplinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de Dados", "Engenharia de Software", "Programação Orientada a Objetos", "Sistemas Operacionais", "Redes de Computadores", " " }));
        cmb_disciplinas.addActionListener(this::cmb_disciplinasActionPerformed);

        lbl_id.setText("ID");

        txt_id.addActionListener(this::txt_idActionPerformed);

        bnt_atualizar.setText("Atualizar");
        bnt_atualizar.addActionListener(this::bnt_atualizarActionPerformed);

        lbl_id2.setText("ID");

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(this::btn_excluirActionPerformed);

        txt_id2.setEnabled(false);
        txt_id2.addActionListener(this::txt_id2ActionPerformed);

        lbl_nome.setText("nome");

        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(this::btn_consultarActionPerformed);

        lbl_idade.setText("idade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_disciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(bnt_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_idade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_idade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_id2)
                                        .addComponent(lbl_id))
                                    .addComponent(lbl_nome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(txt_id)
                                    .addComponent(txt_id2))))
                        .addGap(47, 47, 47)
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idade)
                    .addComponent(txt_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_disciplina)
                    .addComponent(cmb_disciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_disciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_disciplinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_disciplinasActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void bnt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_atualizarActionPerformed
        Professor p = new Professor();
        p.setId(Integer.parseInt(txt_id2.getText()));
        p.setNome(txt_nome.getText());
        p.setIdade(Integer.parseInt(txt_idade.getText()));
        p.setDisciplina(cmb_disciplinas.getSelectedItem().toString());

        ProfessorDAO pDAO = new ProfessorDAO();
        pDAO.editar(p);
        limparFormulario();
    }//GEN-LAST:event_bnt_atualizarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir esse registro?", "Excluão", JOptionPane.YES_NO_OPTION);
        if(resposta == JOptionPane.YES_OPTION){
            ProfessorDAO pDAO = new ProfessorDAO();
            pDAO.excluir(Integer.parseInt(txt_id2.getText()));
            limparFormulario();
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void txt_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id2ActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        int idProfessor = Integer.parseInt(txt_id.getText());
        ProfessorDAO pDAO = new ProfessorDAO();

        Professor p = pDAO.getProfessor(idProfessor);
        if(p == null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Professor nao encontrado");
        }
        else{
            txt_id2.setText(p.getId()+"");
            txt_nome.setText(p.getNome());
            txt_idade.setText(String.valueOf(p.getIdade()));
            cmb_disciplinas.setSelectedItem(p.getDisciplina());
        }
    }//GEN-LAST:event_btn_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormConsultaProfessor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_atualizar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JComboBox<String> cmb_disciplinas;
    private javax.swing.JLabel lbl_disciplina;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_id2;
    private javax.swing.JLabel lbl_idade;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id2;
    private javax.swing.JTextField txt_idade;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
